name: Testing
version: 1.0
author: JayReturns
description: McUniverse Testing
main: eu.mcuniverse.testing.main.Main
loadbefore: [ProtocolLib]
depend: [ProtocolLib]
api-version: 1.15

commands:
  dimension:
  # nbt:
  oil: