name: Weapon
author: JayReturns
version: 0.0.2-SNAPHOST
api-version: 1.15
main: eu.mcuniverse.weapons.main.Core
loadbefore: [ProtocolLib, UniverseAPI]
depend: [ProtocolLib, UniverseAPI]

commands:
  weaponadmin:
    permission: mcuniverse.weapon.admin
    usage: /weaponadmin
    description: Weaponadmin command
    aliases: [wa]
  resource:
    usage: /resource
    description: Set the resourcepack
    alias: [resourcepack]